name: premiere
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.9
  flutter_full_pdf_viewer: ^1.0.4
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  image_picker: ^0.6.7+22
  otp_text_field: ^1.0.2
  country_picker: ^1.1.4
  firebase_messaging: ^6.0.15


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - android/app/src/main/res/mipmap-mdpi/
    # #Serie A :
    # # Anglais
    # - assets/pdf/serie A/Anglais/cours/
    # - assets/pdf/serie A/Anglais/exercices/
    # - assets/pdf/serie A/Anglais/tp/
    # # Chimie
    # - assets/pdf/serie A/Chimie/cours/
    # - assets/pdf/serie A/Chimie/exercices/
    # - assets/pdf/serie A/Chimie/tp/
    # # Francais
    # - assets/pdf/serie A/Francais/cours/
    # - assets/pdf/serie A/Francais/exercices/
    # - assets/pdf/serie A/Francais/tp/
    # # Informatique
    # - assets/pdf/serie A/Informatique/cours/
    # - assets/pdf/serie A/Informatique/exercices/
    # - assets/pdf/serie A/Informatique/tp/
    # # Mathematique
    # - assets/pdf/serie A/Math/cours/
    # - assets/pdf/serie A/Math/exercices/
    # - assets/pdf/serie A/Math/tp/
    # # Physique
    # - assets/pdf/serie A/Physique/cours/
    # - assets/pdf/serie A/Physique/exercices/
    # - assets/pdf/serie A/Physique/tp/
    # # SVT
    # - assets/pdf/serie A/SVT/cours/
    # - assets/pdf/serie A/SVT/exercices/
    # - assets/pdf/serie A/SVT/tp/
    # #Serie C :
    # # Anglais
    # - assets/pdf/serie A/Anglais/cours/
    # - assets/pdf/serie A/Anglais/exercices/
    # - assets/pdf/serie A/Anglais/tp/
    # # Chimie
    # - assets/pdf/serie A/Chimie/cours/
    # - assets/pdf/serie A/Chimie/exercices/
    # - assets/pdf/serie A/Chimie/tp/
    # # Francais
    # - assets/pdf/serie A/Francais/cours/
    # - assets/pdf/serie A/Francais/exercices/
    # - assets/pdf/serie A/Francais/tp/
    # # Informatique
    # - assets/pdf/serie A/Informatique/cours/
    # - assets/pdf/serie A/Informatique/exercices/
    # - assets/pdf/serie A/Informatique/tp/
    # # Mathematique
    # - assets/pdf/serie A/Math/cours/
    # - assets/pdf/serie A/Math/exercices/
    # - assets/pdf/serie A/Math/tp/
    # # Physique
    # - assets/pdf/serie A/Physique/cours/
    # - assets/pdf/serie A/Physique/exercices/
    # - assets/pdf/serie A/Physique/tp/
    # # SVT
    # - assets/pdf/serie A/SVT/cours/
    # - assets/pdf/serie A/SVT/exercices/
    # - assets/pdf/serie A/SVT/tp/
    # #Serie D :
    # # Anglais
    # - assets/pdf/serie A/Anglais/cours/
    # - assets/pdf/serie A/Anglais/exercices/
    # - assets/pdf/serie A/Anglais/tp/
    # # Chimie
    # - assets/pdf/serie A/Chimie/cours/
    # - assets/pdf/serie A/Chimie/exercices/
    # - assets/pdf/serie A/Chimie/tp/
    # # Francais
    # - assets/pdf/serie A/Francais/cours/
    # - assets/pdf/serie A/Francais/exercices/
    # - assets/pdf/serie A/Francais/tp/
    # # Informatique
    # - assets/pdf/serie A/Informatique/cours/
    # - assets/pdf/serie A/Informatique/exercices/
    # - assets/pdf/serie A/Informatique/tp/
    # # Mathematique
    # - assets/pdf/serie A/Math/cours/
    # - assets/pdf/serie A/Math/exercices/
    # - assets/pdf/serie A/Math/tp/
    # # Physique
    # - assets/pdf/serie A/Physique/cours/
    # - assets/pdf/serie A/Physique/exercices/
    # - assets/pdf/serie A/Physique/tp/
    # # SVT
    # - assets/pdf/serie A/SVT/cours/
    # - assets/pdf/serie A/SVT/exercices/
    # - assets/pdf/serie A/SVT/tp/
    # #Serie E :
    # # Anglais
    # - assets/pdf/serie A/Anglais/cours/
    # - assets/pdf/serie A/Anglais/exercices/
    # - assets/pdf/serie A/Anglais/tp/
    # # Chimie
    # - assets/pdf/serie A/Chimie/cours/
    # - assets/pdf/serie A/Chimie/exercices/
    # - assets/pdf/serie A/Chimie/tp/
    # # Francais
    # - assets/pdf/serie A/Francais/cours/
    # - assets/pdf/serie A/Francais/exercices/
    # - assets/pdf/serie A/Francais/tp/
    # # Informatique
    # - assets/pdf/serie A/Informatique/cours/
    # - assets/pdf/serie A/Informatique/exercices/
    # - assets/pdf/serie A/Informatique/tp/
    # # Mathematique
    # - assets/pdf/serie A/Math/cours/
    # - assets/pdf/serie A/Math/exercices/
    # - assets/pdf/serie A/Math/tp/
    # # Physique
    # - assets/pdf/serie A/Physique/cours/
    # - assets/pdf/serie A/Physique/exercices/
    # - assets/pdf/serie A/Physique/tp/
    # # SVT
    # - assets/pdf/serie A/SVT/cours/
    # - assets/pdf/serie A/SVT/exercices/
    # - assets/pdf/serie A/SVT/tp/
    # #Serie TI :
    # # Anglais
    # - assets/pdf/serie A/Anglais/cours/
    # - assets/pdf/serie A/Anglais/exercices/
    # - assets/pdf/serie A/Anglais/tp/
    # # Chimie
    # - assets/pdf/serie A/Chimie/cours/
    # - assets/pdf/serie A/Chimie/exercices/
    # - assets/pdf/serie A/Chimie/tp/
    # # Francais
    # - assets/pdf/serie A/Francais/cours/
    # - assets/pdf/serie A/Francais/exercices/
    # - assets/pdf/serie A/Francais/tp/
    # # Informatique
    # - assets/pdf/serie A/Informatique/cours/
    # - assets/pdf/serie A/Informatique/exercices/
    # - assets/pdf/serie A/Informatique/tp/
    # # Mathematique
    # - assets/pdf/serie A/Math/cours/
    # - assets/pdf/serie A/Math/exercices/
    # - assets/pdf/serie A/Math/tp/
    # # Physique
    # - assets/pdf/serie A/Physique/cours/
    # - assets/pdf/serie A/Physique/exercices/
    # - assets/pdf/serie A/Physique/tp/
    # # SVT
    # - assets/pdf/serie A/SVT/cours/
    # - assets/pdf/serie A/SVT/exercices/
    # - assets/pdf/serie A/SVT/tp/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
